# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: cron job

on:
  schedule:
    - cron: '5 * * * *'
  push:
    branches: ['main']

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: |
          curl --request POST \
          --url 'https://cron-job.vercel.app/api/corn' \
          --header 'Authorization: Bearer ${{ secrets.API_SECRET_KEY }}'
