# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: cron job

on:
  workflow_dispatch:
  schedule:
    # 约每天早上8点触发（UTC时间0点）
    - cron: '0 0 * * *'

jobs:
  cron:
    # https://github.com/puppeteer/puppeteer/issues/12818
    runs-on: ubuntu-22.04
    env:
      JUEJIN_COOKIE_JSON: ${{ secrets.JUEJIN_COOKIE_JSON }}
      EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
      EMAIL_TO: ${{ secrets.EMAIL_TO }}
      EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
      EMAIL_USER: ${{ secrets.EMAIL_USER }}
    steps:
      - name: 安装中文字体
        run: sudo apt install -y --force-yes --no-install-recommends ttf-wqy-microhei
      - uses: actions/checkout@v2
      - name: 安装依赖
        run: yarn
      - name: 运行脚本
        run: yarn start
