# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: cron job

on:
  push:
    branches:
      - main

jobs:
  # juejin:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Call our API route
  #       run: |
  #         curl --request POST \
  #         --url 'https://cron-job.vercel.app/api/corn' \
  #         --header 'Authorization: Bearer ${{ secrets.API_SECRET_KEY }}'
  algolia:
    runs-on: ubuntu-latest
    steps:
      - name: algolia-docsearch
          env:
            APPLICATION_ID: ${{ secrets.ALGOLIA_APP_ID }}
            API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
        run: |
          docker run \
            -it \
            --env APPLICATION_ID=${secrets.APPLICATION_ID} \
            --env API_KEY=${secrets.API_KEY} \
            --env "CONFIG=$(cat docsearch.json | jq -r tostring)" \
            algolia/docsearch-scraper
